import React from "react";
import vocatImg from "../assets/VOCAT.png";
import vocaiImg from "../assets/VOCAI.png";
import vocopImg from "../assets/VOCOP.png";
import AnimatedSection from "../UI/AnimatedSection";
import "../App.css";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";

const products = [
  {
    name: "VOCAT",
    desc: "VOCAT is a specialized software application designed for creating custom voice datasets. By learning from diverse voice samples, it enables users to generate personalized datasets—whether using their own voice or that of others—empowering deeper interaction and innovation with voice technology.",
    img: vocatImg
  },
  {
    name: "VOCAI",
    desc: "VOCAI is a software platform designed to create personalized voice datasets. By learning from a wide array of voice samples, it enables users to generate custom voice profiles—whether their own or those of others—fostering deeper engagement with voice-driven technologies.",
    img: vocaiImg
  },
  {
    name: "VOCOP",
    desc: "VOCAP is an automated audio watermarking system that embeds a unique, traceable signature into every audio file generated by VOCAI.",
    img: vocopImg
  }
];

function ProductShowcase() {
  const navigate = useNavigate();

  return (
    <section className="product-showcase">
      <AnimatedSection>
      <h2>Explore Our Products</h2>
      </AnimatedSection>
      <div id="vocat" className="product-row-2col" key={products[0].name}>
        <div className="product-info">
          <h3 className="product-title-shadow">{products[0].name}</h3>
          <p className="product-desc-text">{products[0].desc}</p>
          <button
            className="download-btn"
            onClick={() => navigate('/login')}
          >
            Download
          </button>
        </div>
        <AnimatedSection>
          <div className="product-image-col">
          <a href="/login">
            <img
              src={products[0].img}
              alt={products[0].name}
              className="product-image-large clickable-image"
            />
          </a>
        </div>
        </AnimatedSection>
      </div>
      <AnimatedSection>
        <div className="vocal-ai-training-section">
        <h2 className="vocal-ai-training-title">Vocal AI Training</h2>
        <div className="vocal-ai-training-steps">
          <div className="vocal-ai-training-step">Insert a<br />Voice-Over<br />Name</div>
          <span className="vocal-ai-training-arrow">→</span>
          <div className="vocal-ai-training-step">Record your voice realtime on the plugin to upload Voice as a "Verified" purchasable Voice-Over</div>
          <span className="vocal-ai-training-arrow">→</span>
          <div className="vocal-ai-training-step">Drag and Drop Zip or Audio File to create an "Unverified" purchasable Voice-Over</div>
          <span className="vocal-ai-training-arrow">→</span>
          <div className="vocal-ai-training-step">Insert basic info for voice-training</div>
          <span className="vocal-ai-training-arrow">→</span>
          <div className="vocal-ai-training-step">Click the train button either "Upload" to VOSTCO or save on "Private" Cloud</div>
        </div>
      </div>
      </AnimatedSection>
      <div id="vocai" className="product-row-2col" key={products[1].name}>
        <div className="product-info">
          <h3 className="product-title-shadow">{products[1].name}</h3>
          <p className="product-desc-text">{products[1].desc}</p>
          <button
            className="download-btn"
            onClick={() => navigate('/login')}
          >
            Download
          </button>
        </div>
        <div className="product-image-col">
          <a href="/login">
            <img
              src={products[1].img}
              alt={products[1].name}
              className="product-image-large clickable-image"
            />
          </a>
        </div>
      </div>
      <AnimatedSection>
        <div className="vocal-ai-training-section">
          <h2 className="vocal-ai-training-title">Vocal Conversion AI</h2>
          <div className="vocal-ai-training-steps">
            <div className="vocal-ai-training-step">Record or Drag and Drop Voice Audio</div>
            <span className="vocal-ai-training-arrow">→</span>
            <div className="vocal-ai-training-step">Select Voice-Over</div>
            <span className="vocal-ai-training-arrow">→</span>
            <div className="vocal-ai-training-step">Select a gender you are converting to 
            ex) M → F, F → M, M → M, F → F</div>
            <span className="vocal-ai-training-arrow">→</span>
            <div className="vocal-ai-training-step">Control Pitch, insert BPM and Key</div>
            <span className="vocal-ai-training-arrow">→</span>
            <div className="vocal-ai-training-step">Click "Convert"</div>
          </div>
        </div>
      </AnimatedSection>
      <AnimatedSection>
      <motion.div
        id="vocop"
        className="product-row-2col"
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.7, ease: "easeOut" }}
        viewport={{ once: true, amount: 0.3 }}
      >
        <div className="product-info">
          <h3 className="product-title-shadow">{products[2].name}</h3>
          <p className="product-desc-text">{products[2].desc}</p>
          <button
            className="download-btn"
            onClick={() => navigate('/login')}
          >
            Download
          </button>
        </div>
        <div className="product-image-col">
          <a href="/login">
            <img
              src={products[2].img}
              alt={products[2].name}
              className="product-image-large clickable-image"
            />
          </a>
        </div>
      </motion.div>
      </AnimatedSection>
    </section>
  );
}

export default ProductShowcase;