import React from "react";
import { useNavigate, Link } from "react-router-dom";
import calliopeImg from "../assets/calliope-ui.png";
import vocatImg from "../assets/VOCAT.png";
import vocaiImg from "../assets/VOCAI.png";
import vocopImg from "../assets/vocop.png";
import AnimatedSection from "../UI/AnimatedSection";
import "../App.css";
import { motion } from "framer-motion";

const products = [
  {
    id: "calliope",
    title: "CALLIOPE AI",
    desc: "Calliope AI powers voice cloning, multilingual dubbing, and vocal modulation, allowing users to speak, sing, or emote in any language with studio-grade realism. Perfect for creators, patients, and global storytellers.",
    img: calliopeImg,
    imgAlt: "Calliope AI UI",
    reverse: false,
  },
  {
    id: "vocat",
    title: "VOCAT",
    desc: "VOCAT is a specialized software application designed for creating custom voice datasets. By learning from diverse voice samples, it enables users to generate personalized datasets—whether using their own voice or that of others—empowering deeper interaction and innovation with voice technology.",
    img: vocatImg,
    imgAlt: "VOCAT UI",
    reverse: true,
  },
  {
    id: "vocai",
    title: "VOCAI",
    desc: "VOCAI is a software platform designed to create personalized voice datasets. By learning from a wide array of voice samples, it enables users to generate custom voice profiles—whether their own or those of others—fostering deeper engagement with voice-driven technologies.",
    img: vocaiImg,
    imgAlt: "VOCAI UI",
    reverse: false,
  },
  {
    id: "vocop",
    title: "VOCOP",
    desc: "VOCAP is an automated audio watermarking system that embeds a unique, traceable signature into every audio file generated by VOCAI.",
    img: vocopImg,
    imgAlt: "VOCOP UI",
    reverse: true,
  },
];

function ProductOverview() {
  const navigate = useNavigate();

  return (
    <motion.div
      initial={{ opacity: 0, y: 40 }}
      whileInView={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.7, ease: "easeOut" }}
      viewport={{ once: true, amount: 0.3 }}
      style={{ margin: "0 10px" }}
    >
      <section className="product-overview-section">
        <AnimatedSection duration={1.5}>
          <h2 className="product-overview-title">Explore Our Products</h2>
        </AnimatedSection>
        {products.map((product) => (
          <AnimatedSection duration={1.5} key={product.id}>
            <div
              className={`product-overview-row${product.reverse ? " reverse" : ""}`}
            >
              <div className="product-overview-image-col">
                <img
                  src={product.img}
                  alt={product.imgAlt}
                  className="product-overview-image"
                />
              </div>
              <div className="product-overview-info">
                <h3 className="product-overview-name">{product.title}</h3>
                <p className="product-overview-desc">{product.desc}</p>
                {product.id === "calliope" ? (
                  <button
                    className="learn-more-btn"
                    onClick={() => navigate("/calliope-ai")}
                  >
                    Learn More →
                  </button>
                ) : product.id === "vocat" ? (
                  <Link to="/vostco#vocat" className="learn-more-btn">
                    Learn More →
                  </Link>
                ) : product.id === "vocai" ? (
                  <button
                    className="learn-more-btn"
                    onClick={() => navigate("/vostco#vocai")}
                  >
                    Learn More →
                  </button>
                ) : (
                  <button
                    className="learn-more-btn"
                    onClick={() => navigate("/vostco#vocop")}
                  >
                    Learn More →
                  </button>
                )}
              </div>
            </div>
          </AnimatedSection>
        ))}
      </section>
    </motion.div>
  );
}

export default ProductOverview;